server:
  port: 3015
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: comment-service
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: comment_db
      port: 27017


